language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - psql -c 'create database imposter' -U postgres
  - cp src/settings/travis.py src/settings/local.py
script:
  - src/manage.py test
  - flake8
addons:
  postgresql: "9.6"
  apt:
    packages:
      - ghostscript
      - imagemagick
