# Generated by Django 2.0.10 on 2019-01-11 22:56

from django.db import migrations


def modify_spec(apps, schema_editor):
    Spec = apps.get_model('imposter', 'PosterSpec')
    for spec in Spec.objects.all():
        spec.editable_fields['event_price']['mandatory'] = False
        spec.save()


class Migration(migrations.Migration):

    dependencies = [
        ('imposter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(modify_spec),
    ]
