# Generated by Django 2.0.10 on 2019-01-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imposter', '0002_modify_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureau',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'ordering': ('-modified',)},
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='print',
            new_name='print_pdf',
        ),
    ]
