# Generated by Django 2.0.10 on 2019-01-12 21:13

from django.db import migrations, models
import functools
import imposter.models.poster


class Migration(migrations.Migration):

    dependencies = [
        ('imposter', '0003_rename_print_to_print_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='print_jpg',
            field=models.FileField(blank=True, editable=False, upload_to=functools.partial(imposter.models.poster.Poster._upload_to, *(), **{'suffix': 'PRINT'})),
        ),
        migrations.AlterField(
            model_name='poster',
            name='print_pdf',
            field=models.FileField(editable=False, upload_to=functools.partial(imposter.models.poster.Poster._upload_to, *(), **{'suffix': 'PRINT'})),
        ),
        migrations.AlterField(
            model_name='poster',
            name='thumb',
            field=models.ImageField(editable=False, upload_to=functools.partial(imposter.models.poster.Poster._upload_to, *(), **{'suffix': 'THUMB'})),
        ),
    ]
