FORMAT: 1A

# Imposter API

## Imposter API root [/api/]

### Retrieve API endpoints [GET]

+ Response 200 (application/json)

        {
            "bureau": "http://domain/api/bureau/",
            "spec": "http://domain/api/spec/",
            "poster": "http://domain/api/poster/"
        }

## Group Bureau

Bureau API endpoint. Only allows listing.

### Bureau collection [/bureau/{?limit,offset}]

+ Parameters
    + limit: 10 (optional, number) - Paging limit
    + offset: 0 (optional, number) - Paging offset

#### List all bureaus [GET]

+ Response 200 (application/json)
    
        [
            {
                "id": 1,
                "name": "\u00dast\u0159edn\u00ed knihovna",
                "abbrev": "USTR",
                "address": "Mari\u00e1nsk\u00e9 n\u00e1m\u011bst\u00ed 98/1, Praha 1"
            },
            {
                "id": 2,
                "name": "Barrandov",
                "abbrev": "BAR",
                "address": "Wassermannova 926/16, Praha 5"
            },
            {
                "id": 3,
                "name": "Bohnice",
                "abbrev": "BOH",
                "address": "T\u011b\u0161\u00ednsk\u00e1 600/4, Praha 8"
            },
            {
                "id": 4,
                "name": "B\u0159evnov",
                "abbrev": "BREV",
                "address": "B\u011blohorsk\u00e1 1666/56, Praha 6"
            },
            {
                "id": 5,
                "name": "Cibulka",
                "abbrev": "CIB",
                "address": "Mus\u00edlkova 335/62, Praha 5"
            }
        ]

## Group Spec

Spec API endpoint. Only allows listing.

### Spec collection [/spec/{?limit,offset}]

+ Parameters
    + limit: 10 (optional, number) - Paging limit
    + offset: 0 (optional, number) - Paging offset

#### List all specs [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Obecn\u00fd let\u00e1k 1",
                "color": "#41B2CC",
                "thumb": "/media/specs/thumbs/obecny-letak-1-thumb.jpg",
                "fields": {
                    "title": {
                        "name": "Titul",
                        "type": "text",
                        "mandatory": true,
                        "char_limit": 20
                    },
                    "summary": {
                        "name": "Anotace",
                        "type": "text",
                        "mandatory": true,
                        "char_limit": 300
                    },
                    "addendum": {
                        "name": "Dodate\u010dn\u00fd text",
                        "type": "text",
                        "char_limit": 75
                    },
                    "subtitle": {
                        "name": "Podtitul",
                        "type": "text",
                        "char_limit": 50
                    },
                    "event_date": {
                        "name": "Datum kon\u00e1n\u00ed akce",
                        "type": "text",
                        "mandatory": true
                    },
                    "main_image": {
                        "name": "Hlavn\u00ed obr\u00e1zek",
                        "type": "image",
                        "width": 186,
                        "height": 106,
                        "mandatory": true
                    },
                    "event_price": {
                        "name": "Cena akce",
                        "type": "text",
                        "mandatory": true
                    },
                    "bureau_address": {
                        "name": "Adresa pobo\u010dky",
                        "type": "text",
                        "mandatory": true
                    },
                    "partner_logo_1": {
                        "name": "Logo partnera 1",
                        "type": "image"
                    },
                    "partner_logo_2": {
                        "name": "Logo partnera 2",
                        "type": "image"
                    },
                    "partner_logo_3": {
                        "name": "Logo partnera 3",
                        "type": "image"
                    }
                }
            }
        ]

## Group Poster

Poster API endpoint. Allows CRUD.

### Poster collection [/poster/{?limit,offset,bureau,spec,since,until}]

+ Parameters
    + limit: 10 (optional, number) - Paging limit
    + offset: 0 (optional, number) - Paging offset
    + bureau: 1 (optional, number) - Bureau ID filter
    + spec: 1 (optional, number) - Spec ID filter
    + since: `2017-01-20T02:33:00+02:00` (optional, string) - Datetime filter
    + until: `2018-01-20T02:33:00+02:00` (optional, string) - Datetime filter

#### List all posters [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "title": "title",
                "thumb": "/media/posters/00001_USTR_title_180125.jpeg",
                "print_pdf": "/media/posters/00001_USTR_title_180125.pdf",
                "bureau": {
                    "id": 1,
                    "name": "\u00dast\u0159edn\u00ed knihovna",
                    "abbrev": "USTR",
                    "address": "Mari\u00e1nsk\u00e9 n\u00e1m\u011bst\u00ed 98/1, Praha 1"
                },
                "spec": {
                    "id": 1,
                    "name": "Obecn\u00fd let\u00e1k 1",
                    "color": "#41B2CC",
                    "thumb": "/media/specs/thumbs/obecny-letak-1-thumb.jpg",
                    "fields": {
                        "title": {
                            "name": "Titul",
                            "type": "text",
                            "mandatory": true,
                            "char_limit": 20
                        },
                        "summary": {
                            "name": "Anotace",
                            "type": "text",
                            "mandatory": true,
                            "char_limit": 300
                        },
                        "addendum": {
                            "name": "Dodate\u010dn\u00fd text",
                            "type": "text",
                            "char_limit": 75
                        },
                        "subtitle": {
                            "name": "Podtitul",
                            "type": "text",
                            "char_limit": 50
                        },
                        "event_date": {
                            "name": "Datum kon\u00e1n\u00ed akce",
                            "type": "text",
                            "mandatory": true
                        },
                        "main_image": {
                            "name": "Hlavn\u00ed obr\u00e1zek",
                            "type": "image",
                            "width": 186,
                            "height": 106,
                            "mandatory": true
                        },
                        "event_price": {
                            "name": "Cena akce",
                            "type": "text",
                            "mandatory": true
                        },
                        "bureau_address": {
                            "name": "Adresa pobo\u010dky",
                            "type": "text",
                            "mandatory": true
                        },
                        "partner_logo_1": {
                            "name": "Logo partnera 1",
                            "type": "image"
                        },
                        "partner_logo_2": {
                            "name": "Logo partnera 2",
                            "type": "image"
                        },
                        "partner_logo_3": {
                            "name": "Logo partnera 3",
                            "type": "image"
                        }
                    }
                },
                "fields": {
                    "title": {
                        "name": "Titul",
                        "text": "title",
                        "type": "text",
                        "mandatory": true,
                        "char_limit": 20
                    },
                    "summary": {
                        "name": "Anotace",
                        "text": "summary",
                        "type": "text",
                        "mandatory": true,
                        "char_limit": 300
                    },
                    "event_date": {
                        "name": "Datum kon\u00e1n\u00ed akce",
                        "text": "date",
                        "type": "text",
                        "mandatory": true
                    },
                    "main_image": {
                        "id": 1,
                        "url": "/media/posters/images/c2db476c337749fe_main.jpeg",
                        "data": null,
                        "name": "Hlavn\u00ed obr\u00e1zek",
                        "type": "image",
                        "width": 186,
                        "height": 106,
                        "filename": null,
                        "mandatory": true
                    },
                    "event_price": {
                        "name": "Cena akce",
                        "text": "price",
                        "type": "text",
                        "mandatory": true
                    },
                    "bureau_address": {
                        "name": "Adresa pobo\u010dky",
                        "text": "address",
                        "type": "text",
                        "mandatory": true
                    },
                    "partner_logo_1": {
                        "id": 2,
                        "url": "/media/posters/images/b41b202098594f2c_logo1.jpeg",
                        "data": null,
                        "name": "Logo partnera 1",
                        "type": "image",
                        "filename": null
                    }
                }
            }
        ]

#### Create a new poster [POST]

+ Request (application/json)

        {
            "bureau": 1,
            "spec": 1,
            "fields": {
                "title": {
                    "text": "title"
                },
                "main_image": {
                    "filename": "main.jpeg",
                    "data": "/9j/4AAQSkZJRgABAQEASABIAA..."
                },
                "event_price": {
                    "text": "price"
                },
                "event_date": {
                    "text": "date"
                },
                "summary": {
                    "text": "summary"
                },
                "bureau_address": {
                    "text": "address"
                },
                "partner_logo_1": {
                    "filename": "logo1.jpeg",
                    "data": "/9j/4AAQSkZJRgABAQEASABIAA..."
                }
            }
        }

+ Response 201 (application/json)
    
        {
            "id": 1,
            "title": "title",
            "bureau": 1,
            "spec": 1,
            "thumb": "/media/posters/00001_USTR_title_180125.jpeg",
            "print_pdf": "/media/posters/00001_USTR_title_180125.pdf",
            "fields": {
                "title": {
                    "name": "Titul",
                    "type": "text",
                    "mandatory": true,
                    "char_limit": 20,
                    "text": "title"
                },
                "summary": {
                    "name": "Anotace",
                    "type": "text",
                    "mandatory": true,
                    "char_limit": 300,
                    "text": "summary"
                },
                "event_date": {
                    "name": "Datum kon\u00e1n\u00ed akce",
                    "type": "text",
                    "mandatory": true,
                    "text": "date"
                },
                "main_image": {
                    "name": "Hlavn\u00ed obr\u00e1zek",
                    "type": "image",
                    "width": 186,
                    "height": 106,
                    "mandatory": true,
                    "filename": null,
                    "data": null,
                    "id": 3,
                    "url": "/media/posters/images/ee3d72f5fa274420_main.jpeg"
                },
                "event_price": {
                    "name": "Cena akce",
                    "type": "text",
                    "mandatory": true,
                    "text": "price"
                },
                "bureau_address": {
                    "name": "Adresa pobo\u010dky",
                    "type": "text",
                    "mandatory": true,
                    "text": "address"
                },
                "partner_logo_1": {
                    "name": "Logo partnera 1",
                    "type": "image",
                    "filename": null,
                    "data": null,
                    "id": 4,
                    "url": "/media/posters/images/d07d3103059c4592_logo1.jpeg"
                }
            }
        }


### Poster detail [/poster/{id}/]

+ Parameters
    + id: 1 (required, number) - ID

#### Read poster detail [GET]

+ Response 200 (application/json)
    
        {
            "id": 1,
            "title": "title",
            "thumb": "/media/posters/00001_USTR_title_180125.jpeg",
            "print_pdf": "/media/posters/00001_USTR_title_180125.pdf",
            "bureau": {
                "id": 1,
                "name": "\u00dast\u0159edn\u00ed knihovna",
                "abbrev": "USTR",
                "address": "Mari\u00e1nsk\u00e9 n\u00e1m\u011bst\u00ed 98/1, Praha 1"
            },
            "spec": {
                "id": 1,
                "name": "Obecn\u00fd let\u00e1k 1",
                "color": "#41B2CC",
                "thumb": "/media/specs/thumbs/obecny-letak-1-thumb.jpg",
                "fields": {
                    "title": {
                        "name": "Titul",
                        "type": "text",
                        "mandatory": true,
                        "char_limit": 20
                    },
                    "summary": {
                        "name": "Anotace",
                        "type": "text",
                        "mandatory": true,
                        "char_limit": 300
                    },
                    "addendum": {
                        "name": "Dodate\u010dn\u00fd text",
                        "type": "text",
                        "char_limit": 75
                    },
                    "subtitle": {
                        "name": "Podtitul",
                        "type": "text",
                        "char_limit": 50
                    },
                    "event_date": {
                        "name": "Datum kon\u00e1n\u00ed akce",
                        "type": "text",
                        "mandatory": true
                    },
                    "main_image": {
                        "name": "Hlavn\u00ed obr\u00e1zek",
                        "type": "image",
                        "width": 186,
                        "height": 106,
                        "mandatory": true
                    },
                    "event_price": {
                        "name": "Cena akce",
                        "type": "text",
                        "mandatory": true
                    },
                    "bureau_address": {
                        "name": "Adresa pobo\u010dky",
                        "type": "text",
                        "mandatory": true
                    },
                    "partner_logo_1": {
                        "name": "Logo partnera 1",
                        "type": "image"
                    },
                    "partner_logo_2": {
                        "name": "Logo partnera 2",
                        "type": "image"
                    },
                    "partner_logo_3": {
                        "name": "Logo partnera 3",
                        "type": "image"
                    }
                }
            },
            "fields": {
                "title": {
                    "name": "Titul",
                    "text": "title",
                    "type": "text",
                    "mandatory": true,
                    "char_limit": 20
                },
                "summary": {
                    "name": "Anotace",
                    "text": "summary",
                    "type": "text",
                    "mandatory": true,
                    "char_limit": 300
                },
                "event_date": {
                    "name": "Datum kon\u00e1n\u00ed akce",
                    "text": "date",
                    "type": "text",
                    "mandatory": true
                },
                "main_image": {
                    "id": 1,
                    "url": "/media/posters/images/84216654a3d94465_main.jpeg",
                    "data": null,
                    "name": "Hlavn\u00ed obr\u00e1zek",
                    "type": "image",
                    "width": 186,
                    "height": 106,
                    "filename": null,
                    "mandatory": true
                },
                "event_price": {
                    "name": "Cena akce",
                    "text": "price",
                    "type": "text",
                    "mandatory": true
                },
                "bureau_address": {
                    "name": "Adresa pobo\u010dky",
                    "text": "address",
                    "type": "text",
                    "mandatory": true
                },
                "partner_logo_1": {
                    "id": 2,
                    "url": "/media/posters/images/572403b51fd24b17_logo1.jpeg",
                    "data": null,
                    "name": "Logo partnera 1",
                    "type": "image",
                    "filename": null
                }
            }
        }

#### Update poster [PATCH]

+ Request (application/json)
    
        {
            "fields": {
                "summary": {
                    "text": "updated"
                },
                "partner_logo_1": {
                    "filename": "logo1_replaced.jpeg",
                    "data": "/9j/4AAQSkZJRgABAQEASABIAA..."
                },
                "partner_logo_2": {
                    "filename": "logo2_added.jpeg",
                    "data": "/9j/4AAQSkZJRgABAQEASABIAA..."
                }
            }
        }


+ Response 200 (application/json)
    
        {
            "id": 1,
            "title": "title",
            "thumb": "/media/posters/00001_USTR_title_180125.jpeg",
            "print_pdf": "/media/posters/00001_USTR_title_180125.pdf",
            "bureau": 1,
            "spec": 1,
            "fields": {
                "title": {
                    "name": "Titul",
                    "type": "text",
                    "mandatory": true,
                    "char_limit": 20,
                    "text": "title"
                },
                "summary": {
                    "name": "Anotace",
                    "type": "text",
                    "mandatory": true,
                    "char_limit": 300,
                    "text": "updated"
                },
                "event_date": {
                    "name": "Datum kon\u00e1n\u00ed akce",
                    "type": "text",
                    "mandatory": true,
                    "text": "date"
                },
                "main_image": {
                    "name": "Hlavn\u00ed obr\u00e1zek",
                    "type": "image",
                    "width": 186,
                    "height": 106,
                    "mandatory": true,
                    "id": 1,
                    "url": "/media/posters/images/9d881488155941fe_main.jpeg",
                    "data": null,
                    "filename": null
                },
                "event_price": {
                    "name": "Cena akce",
                    "type": "text",
                    "mandatory": true,
                    "text": "price"
                },
                "bureau_address": {
                    "name": "Adresa pobo\u010dky",
                    "type": "text",
                    "mandatory": true,
                    "text": "address"
                },
                "partner_logo_1": {
                    "name": "Logo partnera 1",
                    "type": "image",
                    "id": 5,
                    "url": "/media/posters/images/4e2a6279fcc04be8_logo1_replaced.jpeg",
                    "data": null,
                    "filename": null
                },
                "partner_logo_2": {
                    "name": "Logo partnera 2",
                    "type": "image",
                    "filename": null,
                    "data": null,
                    "id": 6,
                    "url": "/media/posters/images/88e2cda8ea4147af_logo2_added.jpeg"
                }
            }
        }

#### Delete poster [DELETE]

+ Response 200 (application/json)
    
        {
            "detail": "Successfully deleted."
        }
